name: ci

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11" ]
    name: python-${{ matrix.python }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup python-${{ matrix.python }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tools
        run: |
          python3 -m pip install -r requirements.txt
      - name: Test
        run: |
          find treebomination -iname "*.py" | grep -v -e "__init__.py" | xargs -L 1 mypy
          find treebomination -iname "*.py" | grep -v -e "__init__.py" | xargs -L 1 python3 -m unittest
